# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Electron CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-on-windows:
    environment: production
    runs-on: windows-2022
    env:
      CSC_IDENTITY_AUTO_DISCOVERY: false
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Setup Node/Yarn
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'

    - name: Install dependencies
      run: npm install --force

    - name: Build electron package
      run: npm run build:win
      env:
         CI: false

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-x64-installer
        path: 'dist/diagrammable*.exe'
  
