# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-on-windows:  
    runs-on: windows-2016
    steps:    
    - uses: actions/checkout@v2
      with: 
        ref: electron
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'yarn'
    - run: yarn electron:package:win

  build-on-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: electron
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'yarn'
    - name: see directory   
    - run: yarn electron:package:linux
   
