# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Electron CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-on-windows:
    environment: production
    runs-on: windows-2022
    env:
      WIN_CSC_LINK: ${{ secrets.WINDOWS_PFX }}
      WIN_CSC_PASSWORD: ${{ secrets.WINDOWS_PFX_PASSWORD }}
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Setup Node/Yarn
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'

    - name: Install dependencies
      run: npm install --force

    - name: Build electron package
      run: npm run electron:package:win
      env:
         CI: false

  build-on-linux:
    environment: production
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Setup Node/Yarn
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build electron package
      run: npm run electron:package:linux
      env:
        CI: false
